[tool.poetry]
name = "shiki-api"
version = "0.1.0"
description = "Shikimori API"
authors = ["veynko <veynko@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
